package com.casemanager.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class manulifeObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("sourceOfBusiness")
	private java.lang.String sourceOfBusiness;
	@org.kie.api.definition.type.Label("basicSumAssured")
	private java.lang.Integer basicSumAssured;
	@org.kie.api.definition.type.Label("priority")
	private java.lang.Integer priority;

	@org.kie.api.definition.type.Label("decision")
	private java.lang.String decision;

	@org.kie.api.definition.type.Label("eRefNo")
	private java.lang.String eRefNo;

	@org.kie.api.definition.type.Label("mongoDocID")
	private java.lang.String mongoDocID;

	@org.kie.api.definition.type.Label("productClass")
	private java.lang.String productClass;

	@org.kie.api.definition.type.Label("productCode")
	private java.lang.String productCode;

	@org.kie.api.definition.type.Label("remarks")
	private java.lang.String remarks;

	@org.kie.api.definition.type.Label("uwLevel")
	private java.lang.Integer uwLevel;

	@org.kie.api.definition.type.Label("uw_role")
	private java.lang.String uw_role;

	@org.kie.api.definition.type.Label("verification_Status")
	private java.lang.Boolean verification_Status;

	@org.kie.api.definition.type.Label("processInstanceId")
	private java.lang.String processInstanceId;

	@org.kie.api.definition.type.Label("hniIndicator")
	private java.lang.String hniIndicator;

	@org.kie.api.definition.type.Label("advisorGroup")
	private java.lang.String advisorGroup;

	@org.kie.api.definition.type.Label("manulifeTimer")
	private java.lang.String manulifeTimer;

	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.Boolean status;

	public manulifeObject() {
	}

	public java.lang.String getSourceOfBusiness() {
		return this.sourceOfBusiness;
	}

	public void setSourceOfBusiness(java.lang.String sourceOfBusiness) {
		this.sourceOfBusiness = sourceOfBusiness;
	}

	public java.lang.Integer getBasicSumAssured() {
		return this.basicSumAssured;
	}

	public void setBasicSumAssured(java.lang.Integer basicSumAssured) {
		this.basicSumAssured = basicSumAssured;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public java.lang.String geteRefNo() {
		return this.eRefNo;
	}

	public void seteRefNo(java.lang.String eRefNo) {
		this.eRefNo = eRefNo;
	}

	public java.lang.String getMongoDocID() {
		return this.mongoDocID;
	}

	public void setMongoDocID(java.lang.String mongoDocID) {
		this.mongoDocID = mongoDocID;
	}

	public java.lang.String getProductClass() {
		return this.productClass;
	}

	public void setProductClass(java.lang.String productClass) {
		this.productClass = productClass;
	}

	public java.lang.String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(java.lang.String productCode) {
		this.productCode = productCode;
	}

	public java.lang.String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}

	public java.lang.Integer getUwLevel() {
		return this.uwLevel;
	}

	public void setUwLevel(java.lang.Integer uwLevel) {
		this.uwLevel = uwLevel;
	}

	public java.lang.String getUw_role() {
		return this.uw_role;
	}

	public void setUw_role(java.lang.String uw_role) {
		this.uw_role = uw_role;
	}

	public java.lang.Boolean getVerification_Status() {
		return this.verification_Status;
	}

	public void setVerification_Status(java.lang.Boolean verification_Status) {
		this.verification_Status = verification_Status;
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getHniIndicator() {
		return this.hniIndicator;
	}

	public void setHniIndicator(java.lang.String hniIndicator) {
		this.hniIndicator = hniIndicator;
	}

	public java.lang.String getAdvisorGroup() {
		return this.advisorGroup;
	}

	public void setAdvisorGroup(java.lang.String advisorGroup) {
		this.advisorGroup = advisorGroup;
	}

	public java.lang.String getManulifeTimer() {
		return this.manulifeTimer;
	}

	public void setManulifeTimer(java.lang.String manulifeTimer) {
		this.manulifeTimer = manulifeTimer;
	}

	public java.lang.Boolean getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Boolean status) {
		this.status = status;
	}

	public manulifeObject(java.lang.String sourceOfBusiness,
			java.lang.Integer basicSumAssured, java.lang.Integer priority,
			java.lang.String decision, java.lang.String eRefNo,
			java.lang.String mongoDocID, java.lang.String productClass,
			java.lang.String productCode, java.lang.String remarks,
			java.lang.Integer uwLevel, java.lang.String uw_role,
			java.lang.Boolean verification_Status,
			java.lang.String processInstanceId, java.lang.String hniIndicator,
			java.lang.String advisorGroup, java.lang.String manulifeTimer,
			java.lang.Boolean status) {
		this.sourceOfBusiness = sourceOfBusiness;
		this.basicSumAssured = basicSumAssured;
		this.priority = priority;
		this.decision = decision;
		this.eRefNo = eRefNo;
		this.mongoDocID = mongoDocID;
		this.productClass = productClass;
		this.productCode = productCode;
		this.remarks = remarks;
		this.uwLevel = uwLevel;
		this.uw_role = uw_role;
		this.verification_Status = verification_Status;
		this.processInstanceId = processInstanceId;
		this.hniIndicator = hniIndicator;
		this.advisorGroup = advisorGroup;
		this.manulifeTimer = manulifeTimer;
		this.status = status;
	}

}