package com.casemanager.newbusiness;

/*package com.casemanager.newbusiness;

import com.casemanager.newbusiness.manulifeObject;


ruleflow-group "computepriority"
rule "15"
when
$manulifeObject:manulifeObject(manulifeObject.sourceOfBusiness=="DIR"&&manulifeObject.basicSumAssured>=0 && manulifeObject.basicSumAssured<=100000)
then
$manulifeObject.setPriority(1);
System.out.println("inside drl");
end;

rule "16"
when
$manulifeObject:manulifeObject(manulifeObject.sourceOfBusiness=="DIR"&&manulifeObject.basicSumAssured>=100001 && manulifeObject.basicSumAssured<=500000)
then
$manulifeObject.setPriority(1);
System.out.println("inside drl");
end;


rule "17"
when
$manulifeObject:manulifeObject(manulifeObject.sourceOfBusiness=="DIR"&&manulifeObject.basicSumAssured>=500001 && manulifeObject.basicSumAssured<=1000000)
then
$manulifeObject.setPriority(3);
System.out.println("inside drl");
end;


rule "18"
when
$manulifeObject:manulifeObject()
then
$manulifeObject.setPriority(3);
System.out.println("inside drl");
end;*/